# use ubuntu 18.04
dist: bionic
language: python
# using python version 3.7
python:
  - "3.7"
services:
  - mysql
before_install:
  - mkdir -p ~/.ssh && echo "Host araxconfig.rtx.ai" > ~/.ssh/config && echo "    StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "Host arax.ncats.io" >> ~/.ssh/config && echo "    StrictHostKeyChecking no" >> ~/.ssh/config
  - echo -e "${TRAVIS_KEY//_/\\n}" > ~/.ssh/id_rsa
  - chmod og-rwx ~/.ssh/id_rsa
  - eval "scp ${CONFIG_HOST}:configv2.json ${TRAVIS_BUILD_DIR}/code/configv2.json"
  - export PATH=$PATH:~/kg2-build/
# command to install python dependencies
install:
  - pip install -r requirements.txt
  - pip install reasoner_validator
#  - python ./code/ARAX/ARAXQuery/ARAX_database_manager.py --slim
# command to run tests
script:
#  - pytest -v ./code/ARAX/test/ --disable-pytest-warnings
  - bash -x ./code/kg2/setup-kg2-build.sh travisci
  - bash -x ./code/kg2/run-validation-tests.sh travisci
