[pytest]
norecursedirs =
    code/code-archive/old-arax-tests
    code/ARAX/Testing
    code/UI/OpenAPI/python-flask-server/openapi_server/test
    code/ARAX/ARAXQuery/Overlay
    code/kg2c/synonymizer_build
