apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "arax.fullname" . }}-configmap
  labels:
    {{- include "arax.labels" . | nindent 4 }}
data:
  download_database.sh: |-
    #!/bin/sh
    # printenv
    # cat /etc/ssh-key/ssh-key-SECRET_FILE
    echo "Calculating MD5 of all files and download if needed... "
    sftp -i /etc/ssh-key/ssh-key-SECRET_FILE -o StrictHostKeyChecking=no -pr team-expander-ops@sftp.transltr.io:/transltr-063208468694-sftp/team-expander/databases/ /
    # tail -f /dev/null
  start_app.sh: |-
    #!/bin/bash
    # rename config file
    cp /configv2/configv2.json /mnt/data/orangeboard/production/RTX/code/config_local.json
    su rt 
    cd /mnt/data/orangeboard/production/RTX 
    sudo python3 code/ARAX/ARAXQuery/ARAX_database_manager.py
    sudo service apache2 start
    sudo service RTX_OpenAPI_production start
    # this line is added to stop container completes with exit code 0
    # tail -f /dev/null

