apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "arax.fullname" . }}-configmap
  labels:
    {{- include "arax.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/*").AsConfig | nindent 2 }}
