apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "arax.fullname" . }}
  labels: 
    {{- include "arax.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "arax.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arax.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arax.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arax.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        # initContainers:
        #   - name: {{ .Chart.Name }}-init-container
        #     image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag | default .Chart.AppVersion }}"
        #     command:
        #       - './download_database.sh'
        #     volumeMounts:
        #       - name: ssh-key-volume
        #         mountPath: "/etc/ssh-key"
        #       - name: {{ include "arax.fullname" . }}-scripts
        #         mountPath: /download_database.sh
        #         subPath: download_database.sh
        #       - name: {{ include "arax.fullname" . }}-pvc
        #         mountPath: /databases
      containers:
        - name: {{ .Chart.Name }}-init-container
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag | default .Chart.AppVersion }}"
          command:
            # - './download_database.sh'
            - 'tail -f /dev/null'
          volumeMounts:
            - name: ssh-key-volume
              mountPath: "/etc/ssh-key"
            - name: {{ include "arax.fullname" . }}-scripts
              mountPath: /download_database.sh
              subPath: download_database.sh
            - name: {{ include "arax.fullname" . }}-pvc
              mountPath: /databases
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - './start_app.sh'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "arax.fullname" . }}-pvc
              mountPath: /mnt/data/orangeboard/databases/
            - name: configv2
              mountPath: /configv2
            - name: {{ include "arax.fullname" . }}-scripts
              mountPath: /start_app.sh
              subPath: start_app.sh
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ssh-key-volume
          secret:
            secretName: sftp-ssh-key
            defaultMode: 256
        - name: {{ include "arax.fullname" . }}-scripts
          configMap:
            name: {{ include "arax.fullname" . }}-configmap
            defaultMode: 0777
        - name: configv2
          configMap:
            name: configv2
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: {{ include "arax.fullname" . }}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
