apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "arax.fullname" . }}
  labels: 
    {{- include "arax.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "arax.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arax.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arax.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "arax.serviceAccountName" . }}
      initContainers:
        - name: {{ .Chart.Name }}-init-container
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command:
            - './download_database.sh'
          volumeMounts:
            - name: ssh-key-volume
              mountPath: "/etc/ssh-key"
            - name: configv2
              mountPath: /configv2
            - name: {{ include "arax.fullname" . }}-scripts
              mountPath: /download_database.sh
              subPath: download_database.sh
            - name: {{ include "arax.fullname" . }}-pvc
              mountPath: /databases
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - './start_app.sh'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "arax.fullname" . }}-pvc
              mountPath: /mnt/data/orangeboard/databases/
            - name: configv2
              mountPath: /configv2
            - name: {{ include "arax.fullname" . }}-scripts
              mountPath: /start_app.sh
              subPath: start_app.sh
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ssh-key-volume
          secret:
            secretName: {{ include "arax.fullname" . }}-secret
            defaultMode: 256
        - name: {{ include "arax.fullname" . }}-scripts
          configMap:
            name: {{ include "arax.fullname" . }}-configmap
            defaultMode: 0777
        - name: configv2
          configMap:
            name: configv2
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: {{ include "arax.fullname" . }}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
