apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "kg2.fullname" . }}-secret
  labels:
    {{- include "kg2.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "secrets/*-secret").AsSecrets | nindent 2 }}
