pipeline {
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    agent {
        node { label 'aws && build && translator && rtx' }
    }
    parameters {
        string(name: 'BUILD_VERSION', defaultValue: '', description: 'The build version to deploy (optional)')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
    }
    triggers {
        pollSCM('H/5 * * * *')
    }
    environment {
        DOCKER_REPO_NAME = "translator-rtx-arax"
        KUBERNETES_BLUE_CLUSTER_NAME = "translator-eks-ci-blue-cluster"
        KUBERNETES_GREEN_CLUSTER_NAME = "translator-eks-ci-green-cluster"
        NAMESPACE = "rtx"
        SECRET_NAME = "sftp-ssh-key"
        CFGFILE2DL = "team-expander-ops@sftp.transltr.io:/transltr-063208468694-sftp/team-expander/config_secrets.json"
        CFGFILE2DL_LOCALPATH = "deploy/arax/configs/config_secrets.json"
        sftp_key = "deploy/arax/secrets/team-expander-ops-sshkey-secret"
    }
    stages {
      stage('Build Version'){
          when { expression { return !params.BUILD_VERSION } }
          steps{
              script {
                  BUILD_VERSION_GENERATED = VersionNumber(
                      versionNumberString: 'v${BUILD_YEAR, XX}.${BUILD_MONTH, XX}${BUILD_DAY, XX}.${BUILDS_TODAY}',
                      projectStartDate:    '1970-01-01',
                      skipFailedBuilds:    true)
                  currentBuild.displayName = BUILD_VERSION_GENERATED
                  env.BUILD_VERSION = BUILD_VERSION_GENERATED
                  env.BUILD = 'true'
              }
          }
      }
      stage('Checkout source code') {
          steps {
              cleanWs()
              checkout scm
          }
      }
      stage('Build and Push Docker Image') {
         when { expression { return env.BUILD == 'true' }}
          steps {
                script {
                    sh "export ENV_BUILD_BRANCH=`git rev-parse --abbrev-ref HEAD`"
                    docker.build(env.DOCKER_REPO_NAME, "--build-arg BUILD_BRANCH=$ENV_BUILD_BRANCH --no-cache ./DockerBuild/")
                    docker.withRegistry('https://853771734544.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:aws-ifx-deploy') {
                        docker.image(env.DOCKER_REPO_NAME).push("${BUILD_VERSION}")
                    }
                }
            }
        }
      stage('Deploy to AWS EKS Blue') {
          steps {
              configFileProvider([
                  configFile(fileId: 'arax.values.ncats.yaml', targetLocation: 'deploy/arax/arax.values.ncats.yaml')
              ]){
                  withCredentials([
                    sshUserPrivateKey(
                      credentialsId: 'team-expander-ops-sshkey',
                      keyFileVariable: 'SECRET_FILE')
                  ]){
                    withAWS(credentials:'aws-ifx-deploy') 
                    {
                        sh '''
                        # Need to save the credential to a file with base64 encoded under deploy/secret
                        cat $SECRET_FILE >> deploy/arax/secrets/team-expander-ops-sshkey-secret
                        sftp -i $SECRET_FILE -o StrictHostKeyChecking=no -p $CFGFILE2DL $CFGFILE2DL_LOCALPATH
                        cp code/config_dbs.json deploy/arax/configs
                        aws --region ${AWS_REGION} eks update-kubeconfig --name ${KUBERNETES_BLUE_CLUSTER_NAME}
                        cd deploy/arax && /bin/bash deploy.sh
                        # aws --region ${AWS_REGION} sts get-caller-identity
                        '''
                    }
                  } 
              }
          }
      }
      stage('Clean Up') {
          steps {
              cleanWs()
          }
      }
    }
}
