# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.q_node import QNode
from openapi_server import util

from openapi_server.models.q_node import QNode  # noqa: E501

class BaseQueryGraph(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nodes=None):  # noqa: E501
        """BaseQueryGraph - a model defined in OpenAPI

        :param nodes: The nodes of this BaseQueryGraph.  # noqa: E501
        :type nodes: Dict[str, QNode]
        """
        self.openapi_types = {
            'nodes': Dict[str, QNode]
        }

        self.attribute_map = {
            'nodes': 'nodes'
        }

        self._nodes = nodes

    @classmethod
    def from_dict(cls, dikt) -> 'BaseQueryGraph':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseQueryGraph of this BaseQueryGraph.  # noqa: E501
        :rtype: BaseQueryGraph
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodes(self):
        """Gets the nodes of this BaseQueryGraph.

        The node specifications. The keys of this map are unique node identifiers and the corresponding values include the constraints on bound nodes.  # noqa: E501

        :return: The nodes of this BaseQueryGraph.
        :rtype: Dict[str, QNode]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this BaseQueryGraph.

        The node specifications. The keys of this map are unique node identifiers and the corresponding values include the constraints on bound nodes.  # noqa: E501

        :param nodes: The nodes of this BaseQueryGraph.
        :type nodes: Dict[str, QNode]
        """
        if nodes is None:
            raise ValueError("Invalid value for `nodes`, must not be `None`")  # noqa: E501

        self._nodes = nodes
