# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Credentials(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, password=None):  # noqa: E501
        """Credentials - a model defined in OpenAPI

        :param username: The username of this Credentials.  # noqa: E501
        :type username: str
        :param password: The password of this Credentials.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'username': str,
            'password': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password'
        }

        self._username = username
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'Credentials':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Credentials of this Credentials.  # noqa: E501
        :rtype: Credentials
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this Credentials.

        Username needed for programmatic access to the remote knowledge graph  # noqa: E501

        :return: The username of this Credentials.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this Credentials.

        Username needed for programmatic access to the remote knowledge graph  # noqa: E501

        :param username: The username of this Credentials.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this Credentials.

        Password needed for programmatic access to the remote knowledge graph  # noqa: E501

        :return: The password of this Credentials.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Credentials.

        Password needed for programmatic access to the remote knowledge graph  # noqa: E501

        :param password: The password of this Credentials.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
