# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.knowledge_graph import KnowledgeGraph
from openapi_server.models.message_terms import MessageTerms
from openapi_server.models.query_graph import QueryGraph
from openapi_server.models.remote_knowledge_graph import RemoteKnowledgeGraph
from openapi_server.models.result import Result
from openapi_server import util

from openapi_server.models.knowledge_graph import KnowledgeGraph  # noqa: E501
from openapi_server.models.message_terms import MessageTerms  # noqa: E501
from openapi_server.models.query_graph import QueryGraph  # noqa: E501
from openapi_server.models.remote_knowledge_graph import RemoteKnowledgeGraph  # noqa: E501
from openapi_server.models.result import Result  # noqa: E501

class Message(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, context=None, type=None, id=None, reasoner_id=None, tool_version=None, schema_version=None, datetime=None, n_results=None, message_code=None, code_description=None, table_column_names=None, original_question=None, restated_question=None, query_type_id=None, terms=None, query_options=None, results=None, query_graph=None, knowledge_graph=None, remote_knowledge_graph=None):  # noqa: E501
        """Message - a model defined in OpenAPI

        :param context: The context of this Message.  # noqa: E501
        :type context: str
        :param type: The type of this Message.  # noqa: E501
        :type type: str
        :param id: The id of this Message.  # noqa: E501
        :type id: str
        :param reasoner_id: The reasoner_id of this Message.  # noqa: E501
        :type reasoner_id: str
        :param tool_version: The tool_version of this Message.  # noqa: E501
        :type tool_version: str
        :param schema_version: The schema_version of this Message.  # noqa: E501
        :type schema_version: str
        :param datetime: The datetime of this Message.  # noqa: E501
        :type datetime: str
        :param n_results: The n_results of this Message.  # noqa: E501
        :type n_results: int
        :param message_code: The message_code of this Message.  # noqa: E501
        :type message_code: str
        :param code_description: The code_description of this Message.  # noqa: E501
        :type code_description: str
        :param table_column_names: The table_column_names of this Message.  # noqa: E501
        :type table_column_names: List[str]
        :param original_question: The original_question of this Message.  # noqa: E501
        :type original_question: str
        :param restated_question: The restated_question of this Message.  # noqa: E501
        :type restated_question: str
        :param query_type_id: The query_type_id of this Message.  # noqa: E501
        :type query_type_id: str
        :param terms: The terms of this Message.  # noqa: E501
        :type terms: MessageTerms
        :param query_options: The query_options of this Message.  # noqa: E501
        :type query_options: object
        :param results: The results of this Message.  # noqa: E501
        :type results: List[Result]
        :param query_graph: The query_graph of this Message.  # noqa: E501
        :type query_graph: List[QueryGraph]
        :param knowledge_graph: The knowledge_graph of this Message.  # noqa: E501
        :type knowledge_graph: List[KnowledgeGraph]
        :param remote_knowledge_graph: The remote_knowledge_graph of this Message.  # noqa: E501
        :type remote_knowledge_graph: List[RemoteKnowledgeGraph]
        """
        self.openapi_types = {
            'context': str,
            'type': str,
            'id': str,
            'reasoner_id': str,
            'tool_version': str,
            'schema_version': str,
            'datetime': str,
            'n_results': int,
            'message_code': str,
            'code_description': str,
            'table_column_names': List[str],
            'original_question': str,
            'restated_question': str,
            'query_type_id': str,
            'terms': MessageTerms,
            'query_options': object,
            'results': List[Result],
            'query_graph': List[QueryGraph],
            'knowledge_graph': List[KnowledgeGraph],
            'remote_knowledge_graph': List[RemoteKnowledgeGraph]
        }

        self.attribute_map = {
            'context': 'context',
            'type': 'type',
            'id': 'id',
            'reasoner_id': 'reasoner_id',
            'tool_version': 'tool_version',
            'schema_version': 'schema_version',
            'datetime': 'datetime',
            'n_results': 'n_results',
            'message_code': 'message_code',
            'code_description': 'code_description',
            'table_column_names': 'table_column_names',
            'original_question': 'original_question',
            'restated_question': 'restated_question',
            'query_type_id': 'query_type_id',
            'terms': 'terms',
            'query_options': 'query_options',
            'results': 'results',
            'query_graph': 'query_graph',
            'knowledge_graph': 'knowledge_graph',
            'remote_knowledge_graph': 'remote_knowledge_graph'
        }

        self._context = context
        self._type = type
        self._id = id
        self._reasoner_id = reasoner_id
        self._tool_version = tool_version
        self._schema_version = schema_version
        self._datetime = datetime
        self._n_results = n_results
        self._message_code = message_code
        self._code_description = code_description
        self._table_column_names = table_column_names
        self._original_question = original_question
        self._restated_question = restated_question
        self._query_type_id = query_type_id
        self._terms = terms
        self._query_options = query_options
        self._results = results
        self._query_graph = query_graph
        self._knowledge_graph = knowledge_graph
        self._remote_knowledge_graph = remote_knowledge_graph

    @classmethod
    def from_dict(cls, dikt) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Message of this Message.  # noqa: E501
        :rtype: Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self):
        """Gets the context of this Message.

        JSON-LD context URI  # noqa: E501

        :return: The context of this Message.
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this Message.

        JSON-LD context URI  # noqa: E501

        :param context: The context of this Message.
        :type context: str
        """

        self._context = context

    @property
    def type(self):
        """Gets the type of this Message.

        Entity type of this message  # noqa: E501

        :return: The type of this Message.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Message.

        Entity type of this message  # noqa: E501

        :param type: The type of this Message.
        :type type: str
        """

        self._type = type

    @property
    def id(self):
        """Gets the id of this Message.

        URI for this message  # noqa: E501

        :return: The id of this Message.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Message.

        URI for this message  # noqa: E501

        :param id: The id of this Message.
        :type id: str
        """

        self._id = id

    @property
    def reasoner_id(self):
        """Gets the reasoner_id of this Message.

        Identifier string of the reasoner that provided this message (one of RTX, Robokop, Indigo, Integrator, etc.)  # noqa: E501

        :return: The reasoner_id of this Message.
        :rtype: str
        """
        return self._reasoner_id

    @reasoner_id.setter
    def reasoner_id(self, reasoner_id):
        """Sets the reasoner_id of this Message.

        Identifier string of the reasoner that provided this message (one of RTX, Robokop, Indigo, Integrator, etc.)  # noqa: E501

        :param reasoner_id: The reasoner_id of this Message.
        :type reasoner_id: str
        """

        self._reasoner_id = reasoner_id

    @property
    def tool_version(self):
        """Gets the tool_version of this Message.

        Version label of the tool that generated this message  # noqa: E501

        :return: The tool_version of this Message.
        :rtype: str
        """
        return self._tool_version

    @tool_version.setter
    def tool_version(self, tool_version):
        """Sets the tool_version of this Message.

        Version label of the tool that generated this message  # noqa: E501

        :param tool_version: The tool_version of this Message.
        :type tool_version: str
        """

        self._tool_version = tool_version

    @property
    def schema_version(self):
        """Gets the schema_version of this Message.

        Version label of this JSON-LD schema  # noqa: E501

        :return: The schema_version of this Message.
        :rtype: str
        """
        return self._schema_version

    @schema_version.setter
    def schema_version(self, schema_version):
        """Sets the schema_version of this Message.

        Version label of this JSON-LD schema  # noqa: E501

        :param schema_version: The schema_version of this Message.
        :type schema_version: str
        """

        self._schema_version = schema_version

    @property
    def datetime(self):
        """Gets the datetime of this Message.

        Datetime string for the time that this message was generated  # noqa: E501

        :return: The datetime of this Message.
        :rtype: str
        """
        return self._datetime

    @datetime.setter
    def datetime(self, datetime):
        """Sets the datetime of this Message.

        Datetime string for the time that this message was generated  # noqa: E501

        :param datetime: The datetime of this Message.
        :type datetime: str
        """

        self._datetime = datetime

    @property
    def n_results(self):
        """Gets the n_results of this Message.

        Total number of results from the query (which may be less than what is returned if limits were placed on the number of results to return)  # noqa: E501

        :return: The n_results of this Message.
        :rtype: int
        """
        return self._n_results

    @n_results.setter
    def n_results(self, n_results):
        """Sets the n_results of this Message.

        Total number of results from the query (which may be less than what is returned if limits were placed on the number of results to return)  # noqa: E501

        :param n_results: The n_results of this Message.
        :type n_results: int
        """

        self._n_results = n_results

    @property
    def message_code(self):
        """Gets the message_code of this Message.

        Set to OK for success, or some other short string to indicate and error (e.g., KGUnavailable, TermNotFound, etc.)  # noqa: E501

        :return: The message_code of this Message.
        :rtype: str
        """
        return self._message_code

    @message_code.setter
    def message_code(self, message_code):
        """Sets the message_code of this Message.

        Set to OK for success, or some other short string to indicate and error (e.g., KGUnavailable, TermNotFound, etc.)  # noqa: E501

        :param message_code: The message_code of this Message.
        :type message_code: str
        """

        self._message_code = message_code

    @property
    def code_description(self):
        """Gets the code_description of this Message.

        Extended description denoting the success or mode of failure in the generation of the message  # noqa: E501

        :return: The code_description of this Message.
        :rtype: str
        """
        return self._code_description

    @code_description.setter
    def code_description(self, code_description):
        """Sets the code_description of this Message.

        Extended description denoting the success or mode of failure in the generation of the message  # noqa: E501

        :param code_description: The code_description of this Message.
        :type code_description: str
        """

        self._code_description = code_description

    @property
    def table_column_names(self):
        """Gets the table_column_names of this Message.

        List of column names that corresponds to the row_data for each result  # noqa: E501

        :return: The table_column_names of this Message.
        :rtype: List[str]
        """
        return self._table_column_names

    @table_column_names.setter
    def table_column_names(self, table_column_names):
        """Sets the table_column_names of this Message.

        List of column names that corresponds to the row_data for each result  # noqa: E501

        :param table_column_names: The table_column_names of this Message.
        :type table_column_names: List[str]
        """

        self._table_column_names = table_column_names

    @property
    def original_question(self):
        """Gets the original_question of this Message.

        The original question text typed in by the user  # noqa: E501

        :return: The original_question of this Message.
        :rtype: str
        """
        return self._original_question

    @original_question.setter
    def original_question(self, original_question):
        """Sets the original_question of this Message.

        The original question text typed in by the user  # noqa: E501

        :param original_question: The original_question of this Message.
        :type original_question: str
        """

        self._original_question = original_question

    @property
    def restated_question(self):
        """Gets the restated_question of this Message.

        A precise restatement of the question, as understood by the Translator, for which the answer applies. The user should verify that the restated question matches the intent of their original question (it might not).  # noqa: E501

        :return: The restated_question of this Message.
        :rtype: str
        """
        return self._restated_question

    @restated_question.setter
    def restated_question(self, restated_question):
        """Sets the restated_question of this Message.

        A precise restatement of the question, as understood by the Translator, for which the answer applies. The user should verify that the restated question matches the intent of their original question (it might not).  # noqa: E501

        :param restated_question: The restated_question of this Message.
        :type restated_question: str
        """

        self._restated_question = restated_question

    @property
    def query_type_id(self):
        """Gets the query_type_id of this Message.

        The query type id if one is known for the query/message (as defined in https://docs.google.com/spreadsheets/d/18zW81wteUfOn3rFRVG0z8mW-ecNhdsfD_6s73ETJnUw/edit#gid=1742835901 )  # noqa: E501

        :return: The query_type_id of this Message.
        :rtype: str
        """
        return self._query_type_id

    @query_type_id.setter
    def query_type_id(self, query_type_id):
        """Sets the query_type_id of this Message.

        The query type id if one is known for the query/message (as defined in https://docs.google.com/spreadsheets/d/18zW81wteUfOn3rFRVG0z8mW-ecNhdsfD_6s73ETJnUw/edit#gid=1742835901 )  # noqa: E501

        :param query_type_id: The query_type_id of this Message.
        :type query_type_id: str
        """

        self._query_type_id = query_type_id

    @property
    def terms(self):
        """Gets the terms of this Message.


        :return: The terms of this Message.
        :rtype: MessageTerms
        """
        return self._terms

    @terms.setter
    def terms(self, terms):
        """Sets the terms of this Message.


        :param terms: The terms of this Message.
        :type terms: MessageTerms
        """

        self._terms = terms

    @property
    def query_options(self):
        """Gets the query_options of this Message.

        Dict of options that can be sent with the query. Options are tool specific and not stipulated here  # noqa: E501

        :return: The query_options of this Message.
        :rtype: object
        """
        return self._query_options

    @query_options.setter
    def query_options(self, query_options):
        """Sets the query_options of this Message.

        Dict of options that can be sent with the query. Options are tool specific and not stipulated here  # noqa: E501

        :param query_options: The query_options of this Message.
        :type query_options: object
        """

        self._query_options = query_options

    @property
    def results(self):
        """Gets the results of this Message.

        List of all returned potential answers for the query posed  # noqa: E501

        :return: The results of this Message.
        :rtype: List[Result]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this Message.

        List of all returned potential answers for the query posed  # noqa: E501

        :param results: The results of this Message.
        :type results: List[Result]
        """

        self._results = results

    @property
    def query_graph(self):
        """Gets the query_graph of this Message.

        QueryGraph object that contains a serialization of a query in the form of a graph  # noqa: E501

        :return: The query_graph of this Message.
        :rtype: List[QueryGraph]
        """
        return self._query_graph

    @query_graph.setter
    def query_graph(self, query_graph):
        """Sets the query_graph of this Message.

        QueryGraph object that contains a serialization of a query in the form of a graph  # noqa: E501

        :param query_graph: The query_graph of this Message.
        :type query_graph: List[QueryGraph]
        """

        self._query_graph = query_graph

    @property
    def knowledge_graph(self):
        """Gets the knowledge_graph of this Message.

        KnowledgeGraph object that contains all the nodes and edges referenced in any of the possible answers to the query  # noqa: E501

        :return: The knowledge_graph of this Message.
        :rtype: List[KnowledgeGraph]
        """
        return self._knowledge_graph

    @knowledge_graph.setter
    def knowledge_graph(self, knowledge_graph):
        """Sets the knowledge_graph of this Message.

        KnowledgeGraph object that contains all the nodes and edges referenced in any of the possible answers to the query  # noqa: E501

        :param knowledge_graph: The knowledge_graph of this Message.
        :type knowledge_graph: List[KnowledgeGraph]
        """

        self._knowledge_graph = knowledge_graph

    @property
    def remote_knowledge_graph(self):
        """Gets the remote_knowledge_graph of this Message.

        Connection information for a remote knowledge graph that is a substitute for local KnowledgeGraph contained in this Message  # noqa: E501

        :return: The remote_knowledge_graph of this Message.
        :rtype: List[RemoteKnowledgeGraph]
        """
        return self._remote_knowledge_graph

    @remote_knowledge_graph.setter
    def remote_knowledge_graph(self, remote_knowledge_graph):
        """Sets the remote_knowledge_graph of this Message.

        Connection information for a remote knowledge graph that is a substitute for local KnowledgeGraph contained in this Message  # noqa: E501

        :param remote_knowledge_graph: The remote_knowledge_graph of this Message.
        :type remote_knowledge_graph: List[RemoteKnowledgeGraph]
        """

        self._remote_knowledge_graph = remote_knowledge_graph
