import sys
def eprint(*args, **kwargs): print(*args, file=sys.stderr, **kwargs)

from openapi_server.models.query_graph import QueryGraph
from openapi_server.models.pathfinder_query_graph import PathfinderQueryGraph

class OneOfQueryGraphPathfinderQueryGraph():
    """NOTE: This class should be auto generated by OpenAPI Generator (https://openapi-generator.tech).
        but it is mysteriously not, so it was hand-coded by Eric Deutsch
    """

    def __new__(cls, *args, **kwargs):

        debug = False

        if debug:
            eprint("DEBUG: Entering OneOfQueryGraphPathfinderQueryGraph.new()")
            eprint(f"DEBUG:   cls={cls}")
            eprint(f"DEBUG:   args={args}")
            eprint(f"DEBUG:   kwargs={kwargs}")

        #### If there is a path in the kwargs, then assume that this should be a PathfinderQueryGraph object
        if 'path_bindings' in kwargs:
            if debug:
                eprint(f"DEBUG: OneOfQueryGraphPathfinderQueryGraph is generating a PathfinderQueryGraph ({PathfinderQueryGraph})")
            pathfinder_query_graph = super().__new__(PathfinderQueryGraph, *args, **kwargs)
            pathfinder_query_graph.__init__(*args, **kwargs)
            return pathfinder_query_graph

        #### Or otherwise a plain QueryGraph object
        else:
            if debug:
                eprint(f"DEBUG: OneOfQueryGraphPathfinderQueryGraph is generating a QueryGraph ({QueryGraph})")
            query_graph = super().__new__(QueryGraph, *args, **kwargs)
            query_graph.__init__(*args, **kwargs)
            return query_graph

