# coding: utf-8

"""
    ARAX Translator Reasoner - TRAPI 2.0.0

    TRAPI 2.0.0-beta2 endpoint for the NCATS Biomedical Translator Reasoner called ARAX

    The version of the OpenAPI document: 2.0.0
    Contact: edeutsch@systemsbiology.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.message import Message
from openapi_server.models.object import object
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Operations(object):
    """
    Container for one or more Message objects or identifiers for one or more Messages along with a processing plan and options for how those messages should be processed and returned
    """ # noqa: E501
    message_uris: Optional[List[StrictStr]] = Field(default=None, description="List of URIs for Message or Response objects to fetch and process")
    messages: Optional[List[Message]] = Field(default=None, description="List of Message objects to process")
    actions: Optional[List[StrictStr]] = Field(default=None, description="List of order-dependent operations to execute")
    options: Optional[Dict[str, Any]] = Field(default=None, description="Map of order independent options that apply during processing")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["message_uris", "messages", "actions", "options"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Operations from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "additional_properties",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item in self.messages:
                if _item:
                    _items.append(_item.to_dict())
            _dict['messages'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Operations from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message_uris": obj.get("message_uris"),
            "messages": [Message.from_dict(_item) for _item in obj.get("messages")] if obj.get("messages") is not None else None,
            "actions": obj.get("actions"),
            "options": obj.get("options")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


