# coding: utf-8

"""
    ARAX Translator Reasoner - TRAPI 2.0.0

    TRAPI 2.0.0-beta2 endpoint for the NCATS Biomedical Translator Reasoner called ARAX

    The version of the OpenAPI document: 2.0.0
    Contact: edeutsch@systemsbiology.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.object import object
from openapi_server.models.path_constraint import PathConstraint
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class QPath(object):
    """
    A path in the QueryGraph used for pathfinder queries. Both subject and object MUST reference QNodes that have a CURIE in their ids property. Paths returned that bind to this QPath MUST represent some relationship between the subject and object.
    """ # noqa: E501
    subject: StrictStr = Field(description="Corresponds to the map key identifier of the subject concept node for the start of the queried path.")
    object: StrictStr = Field(description="Corresponds to the map key identifier of the object concept node for the end of the queried path.")
    predicates: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = Field(default=None, description="QPath predicates are intended to convey what type of paths are desired, NOT a constraint on the types of predicates that may be in result paths. If no predicate is listed, the ARA SHOULD find paths such that the relationship represented by the path is a \"related_to\" relationship. These should be Biolink Model predicates and are allowed to be of type 'abstract' or 'mixin'. Use of 'deprecated' predicates SHOULD be avoided.")
    constraints: Optional[Annotated[List[PathConstraint], Field(min_length=1)]] = Field(default=None, description="A list of constraints for the QPath. If multiple constraints are listed, it should be interpreted as an OR relationship. Each path returned MUST comply with at least one constraint.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["subject", "object", "predicates", "constraints"]

    @field_validator('predicates')
    def predicates_items_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        for item in value:
            if not re.match(r"^biolink:[a-z][a-z_]*$", item):
                raise ValueError(r"must validate the regular expression /^biolink:[a-z][a-z_]*$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QPath from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "additional_properties",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in constraints (list)
        _items = []
        if self.constraints:
            for _item in self.constraints:
                if _item:
                    _items.append(_item.to_dict())
            _dict['constraints'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of QPath from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subject": obj.get("subject"),
            "object": obj.get("object"),
            "predicates": obj.get("predicates"),
            "constraints": [PathConstraint.from_dict(_item) for _item in obj.get("constraints")] if obj.get("constraints") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


