# coding: utf-8

"""
    ARAX Translator Reasoner - TRAPI 2.0.0

    TRAPI 2.0.0-beta2 endpoint for the NCATS Biomedical Translator Reasoner called ARAX

    The version of the OpenAPI document: 2.0.0
    Contact: edeutsch@systemsbiology.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.log_level import LogLevel
from openapi_server.models.object import object
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class QueryParameters(object):
    """
    Query-time parameters that don't affect the semantics of a query or intended workflow, but may affect overall behavior of the server in the execution of this query. The server MUST repeat the parameters it is given in its Response.
    """ # noqa: E501
    timeout: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Custom time in seconds that the client is willing to wait for a response. After this time has elapsed, the service MAY consider the query failed and respond with logs indicating as such. If the service knows it cannot respond in the given time, it MAY respond with an HTTP 409 and a response explaining its time capabilities. Negative values SHOULD be interpreted as disabling any default timeout the server implements.")
    log_level: Optional[LogLevel] = Field(default=None, description="The least critical level of logs to return.")
    bypass_cache: Optional[StrictBool] = Field(default=False, description="Set to true in order to request that the agent obtain fresh information from its sources in all cases where it has a viable choice between requesting fresh information in real time and using cached information. The agent receiving this flag MUST also include it in TRAPI sent to downstream sources (e.g., ARS -> ARAs -> KPs).")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["timeout", "log_level", "bypass_cache"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QueryParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "additional_properties",
            },
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of QueryParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timeout": obj.get("timeout"),
            "log_level": obj.get("log_level"),
            "bypass_cache": obj.get("bypass_cache") if obj.get("bypass_cache") is not None else False
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


