# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.q_edge import QEdge
from openapi_server.models.q_node import QNode
from openapi_server import util

from openapi_server.models.q_edge import QEdge  # noqa: E501
from openapi_server.models.q_node import QNode  # noqa: E501
from openapi_server.models.q_path import QPath  # noqa: E501

class QueryGraph(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nodes=None, edges=None, paths=None):  # noqa: E501
        """QueryGraph - a model defined in OpenAPI

        :param nodes: The nodes of this QueryGraph.  # noqa: E501
        :type nodes: Dict[str, QNode]
        :param edges: The edges of this QueryGraph.  # noqa: E501
        :type edges: Dict[str, QEdge]
        :param paths: The paths of this QueryGraph.  # noqa: E501
        :type paths: Dict[str, QPath]
        """
        self.openapi_types = {
            'nodes': Dict[str, QNode],
            'edges': Dict[str, QEdge],
            'paths': Dict[str, QPath]
        }

        self.attribute_map = {
            'nodes': 'nodes',
            'edges': 'edges',
            'paths': 'paths'
        }

        self._nodes = nodes
        self._edges = edges
        self._paths = paths

    @classmethod
    def from_dict(cls, dikt) -> 'QueryGraph':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryGraph of this QueryGraph.  # noqa: E501
        :rtype: QueryGraph
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodes(self):
        """Gets the nodes of this QueryGraph.

        The node specifications. The keys of this map are unique node identifiers and the corresponding values include the constraints on bound nodes.  # noqa: E501

        :return: The nodes of this QueryGraph.
        :rtype: Dict[str, QNode]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this QueryGraph.

        The node specifications. The keys of this map are unique node identifiers and the corresponding values include the constraints on bound nodes.  # noqa: E501

        :param nodes: The nodes of this QueryGraph.
        :type nodes: Dict[str, QNode]
        """
        if nodes is None:
            raise ValueError("Invalid value for `nodes`, must not be `None`")  # noqa: E501

        self._nodes = nodes

    @property
    def edges(self):
        """Gets the edges of this QueryGraph.

        The edge specifications. The keys of this map are unique edge identifiers and the corresponding values include the constraints on bound edges, in addition to specifying the subject and object QNodes.  # noqa: E501

        :return: The edges of this QueryGraph.
        :rtype: Dict[str, QEdge]
        """
        return self._edges

    @edges.setter
    def edges(self, edges):
        """Sets the edges of this QueryGraph.

        The edge specifications. The keys of this map are unique edge identifiers and the corresponding values include the constraints on bound edges, in addition to specifying the subject and object QNodes.  # noqa: E501

        :param edges: The edges of this QueryGraph.
        :type edges: Dict[str, QEdge]
        """

        self._edges = edges

    @property
    def paths(self):
        """Gets the paths of this QueryGraph.

        The path specifications. The keys of this map are unique edge identifiers and the corresponding values include the constraints on bound edges, in addition to specifying the subject and object QNodes.  # noqa: E501

        :return: The paths of this QueryGraph.
        :rtype: Dict[str, QPath]
        """
        return self._paths

    @paths.setter
    def paths(self, paths):
        """Sets the paths of this QueryGraph.

        The path specifications. The keys of this map are unique edge identifiers and the corresponding values include the constraints on bound edges, in addition to specifying the subject and object QNodes.  # noqa: E501

        :param paths: The edges of this QueryGraph.
        :type paths: Dict[str, QPath]
        """

        self._paths = paths
