apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-auth
  namespace: rtx
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: 
    -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAxvX6YFhJKb4RLyC5j99ooQiy3Dmc2bLqjplM2BK7LpPCbWv93kaZ
3NZVQ0qbsBv7ANlLtNLcXzHv0Sw+cCLSUzV1oL8xPhb0SH1wSGzZ1DllO0ypKpnQW6U9JO
d8R5yoNXYyEXnWSzHGRMcU7oVzIjm662tpXKu8u0aW42EwlqxxjYcRHyoEXzKYZ8zhnUbb
ftJh1/324N4Y9u3CdiCwUp2M0TknMOpSl/sAUr0iPPVgraA2uTParFsz+5NXkZbCxR45QV
SzPOEzlOtg2Y+zHRZJKm14kZFzX5pUs92OZYPkXroSzpu4pTiaO5WCBfsoGDMRdovs1w8h
awTGcwTzeFf/UGzkOAumrFYKV10m0hq+pSrgQY9wtxPxlEtq66APovdYV5pr6SXFTYaEJJ
l/g5yOQFS6MBUkWe44VgSuV6WFNLXmq07kSs9ROJ4v+4db8RLVUO7jIytJ1DKFq+9aj8pe
XrZtSVnkYf9Gk9i4eIzbr2gpzen+/Eg6JyR6ckTnAAAFiJVINs+VSDbPAAAAB3NzaC1yc2
EAAAGBAMb1+mBYSSm+ES8guY/faKEIstw5nNmy6o6ZTNgSuy6Twm1r/d5GmdzWVUNKm7Ab
+wDZS7TS3F8x79EsPnAi0lM1daC/MT4W9Eh9cEhs2dQ5ZTtMqSqZ0FulPSTnfEecqDV2Mh
F51ksxxkTHFO6FcyI5uutraVyrvLtGluNhMJascY2HER8qBF8ymGfM4Z1G237SYdf99uDe
GPbtwnYgsFKdjNE5JzDqUpf7AFK9Ijz1YK2gNrkz2qxbM/uTV5GWwsUeOUFUszzhM5TrYN
mPsx0WSSpteJGRc1+aVLPdjmWD5F66Es6buKU4mjuVggX7KBgzEXaL7NcPIWsExnME83hX
/1Bs5DgLpqxWClddJtIavqUq4EGPcLcT8ZRLauugD6L3WFeaa+klxU2GhCSZf4OcjkBUuj
AVJFnuOFYErlelhTS15qtO5ErPUTieL/uHW/ES1VDu4yMrSdQyhavvWo/KXl62bUlZ5GH/
RpPYuHiM269oKc3p/vxIOickenJE5wAAAAMBAAEAAAGBAMDFT2PN5oVlPK0W3fPCGFP+Y5
3wzEI5kf28FrI749SLIZR3T6/vY+COYmoifZoyYg4+e5WlwBMUBTH71js74eDxKRkoZgOs
pd8eeo4RuTRgr+62pik6gqBpB0ccalPQO0IhVP2NuM1+WoYFBgjcj+MXYD39AkbhtqkVCd
khL7ytNBBWT4aMZVP/Z58a6XZDUyQbnuVxkaPqTPHjB8kAfxZsxCVrZMeGIaRTc8q2qde6
P4O6eYsT7MmWTFVyOyQ6lqKcrEj8VKX+JVuLepAQmMeHDENH0JSj6h+mj9XRW89cczTSh6
H6zQkmNEmcMHg3TQfRbruq97G2y+CxrY3/ZBcXSAO8s4nagwfNDzoivBrqhupYYgioTbzd
pQ9DSNkmylWoW2ZXgZuqkP3DzOFgr7JLusLEIf36AvjLDWpoLhKEQaW4vd2rHmkLeBM+MK
gm9XP1WTT17tbcIQXQSH8sXHSRO47hJAXl3GMlyt9vcSNcdzsJ6PZ40g/sXXrRbHz8cQAA
AMBoNkd0paqQpHSkBG96cNn6m9GFUKAIR9bgp8PUYzKp9hDhxJUUEWVtyBZf7bEZY5mBxq
xXVHXqBiha54eNNIly5abyDjzrtKASVuy6JDCGur3VBK4P0Uyd5DKjnz7DxD6ig69ISBDr
R+w/1ylgYmTNX09LEFKMXgB9fPwWcg+ZZqmi5tbXElrdd2zAdiYZqZUn2iCA1FDIxxOllt
QOMbBQNSQKv93xVZCD28xyza6rZz4CPt9ReiHeOCzGcgNRemcAAADBAORmGc4X3dpkahWg
04TCFYEpgQKfxb1rF2/NxX53jXTePkUQSQp/OrgW8h9/vjqeNrmmf0S/OLIRr5MV3Psm0a
7c5Ji/eFECSZc79SGYZsUo93vdvu7aDHCvhLpy9GKdXvRowvqXbrIsePVJMslLxrYuutrm
7enIUlKUP9tj5faKNORlijN/gNDY9KJoA5F+YGAMN6F9GqBB2b7OaUdOQNcBONYKzCyxQt
UE8JYRxEPH7whI/VMtqfEsGDzj87RALQAAAMEA3wEqB877OWbqBH4fySzjN/Uevs/JmPSf
N9uG4LKCXkxQV63A4NjSL/qVnxYvDNA30kuODbvi5oe3Axbrui0QD+RE0dTrDsGEOm0hUP
Mtae1gSXPIqdrR13oNFpOYKk0TX8raGYTGfBltd5gjvPWWFhK3AvcKFkZ+uV0XGvvEN0Pj
J1Gc1+NFsKwFp28C//80HEAsvgCJJ76x7aJNLYu57012x1fdXUk94HjZIIMp9ebWB4NmXz
uZrszVNnIy3/HjAAAAEXRlYW0tZXhwYW5kZXItZWtzAQ==
-----END OPENSSH PRIVATE KEY-----
