# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.result_feedback import ResultFeedback  # noqa: F401,E501
from swagger_server import util


class ResponseFeedback(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, result_feedback_list: List[ResultFeedback]=None):  # noqa: E501
        """ResponseFeedback - a model defined in Swagger

        :param result_feedback_list: The result_feedback_list of this ResponseFeedback.  # noqa: E501
        :type result_feedback_list: List[ResultFeedback]
        """
        self.swagger_types = {
            'result_feedback_list': List[ResultFeedback]
        }

        self.attribute_map = {
            'result_feedback_list': 'result_feedback_list'
        }

        self._result_feedback_list = result_feedback_list

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseFeedback':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseFeedback of this ResponseFeedback.  # noqa: E501
        :rtype: ResponseFeedback
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_feedback_list(self) -> List[ResultFeedback]:
        """Gets the result_feedback_list of this ResponseFeedback.


        :return: The result_feedback_list of this ResponseFeedback.
        :rtype: List[ResultFeedback]
        """
        return self._result_feedback_list

    @result_feedback_list.setter
    def result_feedback_list(self, result_feedback_list: List[ResultFeedback]):
        """Sets the result_feedback_list of this ResponseFeedback.


        :param result_feedback_list: The result_feedback_list of this ResponseFeedback.
        :type result_feedback_list: List[ResultFeedback]
        """

        self._result_feedback_list = result_feedback_list
